# Generated by Django 4.2.30 on 2026-05-29 11:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("db", "0001_initial"),  # Plane's base models
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified At"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("agent_id", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("event_count", models.IntegerField(default=0)),
                ("total_tokens_in", models.IntegerField(default=0)),
                ("total_tokens_out", models.IntegerField(default=0)),
                ("total_cost", models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created_by", to="db.user")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated_by", to="db.user")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_workspace", to="db.workspace")),
            ],
            options={
                "verbose_name": "Agent Session",
                "verbose_name_plural": "Agent Sessions",
                "db_table": "memoyi_agent_sessions",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="AgentMemory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified At"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content", models.TextField()),
                (
                    "memory_type",
                    models.CharField(
                        choices=[
                            ("fact", "Fact"),
                            ("preference", "Preference"),
                            ("conversation", "Conversation"),
                            ("project", "Project"),
                            ("task", "Task"),
                        ],
                        default="fact",
                        max_length=50,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("importance", models.FloatField(default=1.0)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created_by", to="db.user")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated_by", to="db.user")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="memoyi.agentsession",
                    ),
                ),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_workspace", to="db.workspace")),
            ],
            options={
                "verbose_name": "Agent Memory",
                "verbose_name_plural": "Agent Memories",
                "db_table": "memoyi_agent_memories",
                "ordering": ("-importance", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="AgentEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified At"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("llm_call", "LLM Call"),
                            ("tool_call", "Tool Call"),
                            ("tool_result", "Tool Result"),
                            ("memory_write", "Memory Write"),
                            ("memory_read", "Memory Read"),
                            ("decision", "Decision"),
                            ("error", "Error"),
                            ("system_prompt", "System Prompt"),
                            ("user_message", "User Message"),
                            ("agent_message", "Agent Message"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("tokens_in", models.IntegerField(default=0)),
                ("tokens_out", models.IntegerField(default=0)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created_by", to="db.user")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated_by", to="db.user")),
                (
                    "parent_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="memoyi.agentevent",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="memoyi.agentsession",
                    ),
                ),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_workspace", to="db.workspace")),
            ],
            options={
                "verbose_name": "Agent Event",
                "verbose_name_plural": "Agent Events",
                "db_table": "memoyi_agent_events",
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(fields=["session", "event_type"], name="memoyi_agen_session_3d8f90_idx"),
                    models.Index(fields=["session", "created_at"], name="memoyi_agen_session_32aa5e_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="agentmemory",
            index=models.Index(fields=["session", "memory_type"], name="memoyi_agen_session_a9e09c_idx"),
        ),
    ]
